// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectoR.Examples.EventStore;

#nullable disable

namespace ProjectoR.Examples.EventStore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240118124703_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectoR.Examples.Common.AmountOfUserPerCityProjection", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("City");

                    b.ToTable("AmountOfUsersPerCity", "Projection");
                });

            modelBuilder.Entity("ProjectoR.Examples.Common.AmountOfUsersPerCountryProjection", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("CountryCode");

                    b.ToTable("AmountOfUsersPerCountry", "Projection");
                });

            modelBuilder.Entity("ProjectoR.Examples.Common.UserProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", "Projection");
                });

            modelBuilder.Entity("ProjectoR.Examples.Common.UserProjection", b =>
                {
                    b.OwnsOne("ProjectoR.Examples.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserProjectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserProjectionId");

                            b1.ToTable("User", "Projection");

                            b1.WithOwner()
                                .HasForeignKey("UserProjectionId");
                        });

                    b.OwnsOne("ProjectoR.Examples.Common.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("UserProjectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Mobile")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserProjectionId");

                            b1.ToTable("User", "Projection");

                            b1.WithOwner()
                                .HasForeignKey("UserProjectionId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInformation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
