name: CI

on:
  pull_request:
    branches: [main, development]
      
jobs:
  build:
    runs-on: ubuntu-latest    
    outputs: 
        Version: ${{ steps.gitversion.outputs.SemVer }}
        CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
        
    #Install and calculate the new version with GitVersion  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion # step id used as reference for output values TEST
      with:
        useConfigFile: true
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
   
    #Build and test
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore 
      run: dotnet restore src/ProjectoR.sln
    - name: Build 
      run: dotnet build src/ProjectoR.sln -p:Version='${{ steps.gitversion.outputs.SemVer }}' --configuration Release --no-restore
    - name: Test 
      run: dotnet test src/ProjectoR.sln --no-build --configuration Release
